# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f26b6f439b792503585ccfa4b16fa4197e999aff7d89ba8be634a3c1fae586ed9fee8e82f794f0c78a437a6a06ba323792ce5cbd752310bff14ba4b1b3dce513

test:
  secret_key_base: 40d82ff55546d328798ab0777017cd2dcb7d8c03d662ce585f0f34aeb1183bd6775e9423807a1470a9229cbcc3e5a79a9bd841b77968db0f435c0e9560893e19

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
